BugTracker/Controllers/BugsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BugTracker.Data;
using BugTracker.Models;
using Microsoft.AspNetCore.Authorization;


namespace BugTracker.Controllers
{
    public class BugsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BugsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Bugs
        public async Task<IActionResult> Index(string SelectedProjects, string SortOrder, string SelectedTickets, string SelectedDescription, string SelectedPriority, string SelectedCreateClosedDate)

        {
            //Sorting and DropDownList

            ViewBag.Projects = String.IsNullOrEmpty(SortOrder) ? "Projects_desc" : "";
            ViewBag.Tickets = SortOrder == "Tickets" ? "Tickets_desc" : "Tickets";
            ViewBag.Description = SortOrder == "Description" ? "Description_desc" : "Description";
            ViewBag.Priority = SortOrder == "Priority" ? "Priority_desc" : "Priority";
            ViewBag.CreateClosedDate = SortOrder == "CreateClosedDate" ? "CreateClosedDate_desc" : "CreateClosedDate";

            var rawData = (from s in _context.Bugs
                           select s).ToList();
            var emp = from s in rawData
                      select s;

            if (!String.IsNullOrEmpty(SelectedProjects))
            {
                emp = emp.Where(s => s.Projects.Trim().Equals(SelectedProjects.Trim()));
            }

            if (!String.IsNullOrEmpty(SelectedTickets))
            {
                emp = emp.Where(s => s.Tickets.Trim().Equals(SelectedTickets.Trim()));
            }
        
            if (!String.IsNullOrEmpty(SelectedPriority))
            {
                emp = emp.Where(s => s.Priority.Trim().Equals(SelectedPriority.Trim()));
            }

            if (!String.IsNullOrEmpty(SelectedDescription))
            {
                emp = emp.Where(s => s.Description.Trim().Equals(SelectedDescription.Trim()));
            }

            if (!String.IsNullOrEmpty(SelectedCreateClosedDate))
            {
                emp = emp.Where(s => s.TimeCreated.ToString().Trim().Equals(SelectedCreateClosedDate.Trim()));
            }

            var UniqueProjects = from s in emp
                                group s by s.Projects into newGroup
                                where newGroup.Key != null
                                orderby newGroup.Key
                                select new { Projects = newGroup.Key };
            ViewBag.UniqueProjects = UniqueProjects.Select(m => new SelectListItem { Value = m.Projects, Text = m.Projects }).ToList();

            var UniqueTickets = from s in emp
                                group s by s.Tickets into newGroup
                                where newGroup.Key != null
                                orderby newGroup.Key
                                select new { Tickets = newGroup.Key };
            ViewBag.UniqueTickets = UniqueTickets.Select(m => new SelectListItem { Value = m.Tickets, Text = m.Tickets }).ToList();

            var UniqueDescription = from s in emp
                                group s by s.Tickets into newGroup
                                where newGroup.Key != null
                                orderby newGroup.Key
                                select new { Description = newGroup.Key };
            ViewBag.UniqueDescription = UniqueDescription.Select(m => new SelectListItem { Value = m.Description, Text = m.Description }).ToList();

            var UniquePriority = from s in emp
                                group s by s.Priority into newGroup
                                where newGroup.Key != null
                                orderby newGroup.Key
                                select new { Priority = newGroup.Key };
            ViewBag.UniquePriority = UniquePriority.Select(m => new SelectListItem { Value = m.Priority, Text = m.Priority }).ToList();

            var UniqueDueDate = from s in emp
                                 group s by s.DueDate into newGroup
                                 orderby newGroup.Key
                                 select new { DueDate = newGroup.Key };
            ViewBag.UniqueDueDate = UniqueDueDate.Select(m => new SelectListItem { Value = m.DueDate.ToString(), Text = m.DueDate.ToString() }).ToList();

            ViewBag.SelectedProjects = SelectedProjects;
            ViewBag.SelectedTickets = SelectedTickets;
            ViewBag.SelectedPriority = SelectedPriority;
            ViewBag.SelectedTickets = SelectedDescription;
            ViewBag.SelectedCreateClosedDate = SelectedCreateClosedDate;


            switch (SortOrder)
            {
                case "Projects_desc":
                    emp = emp.OrderByDescending(s => s.Projects);
                    break;

                case "Projects":
                    emp = emp.OrderBy(s => s.Projects);
                    break;

                case "Tickets_desc":
                    emp = emp.OrderByDescending(s => s.Tickets);
                    break;

                case "Tickets":
                    emp = emp.OrderBy(s => s.Tickets);
                    break;

                case "Description_desc":
                    emp = emp.OrderByDescending(s => s.Description);
                    break;

                case "Description":
                    emp = emp.OrderBy(s => s.Description);
                    break;

                case "Priority_desc":
                    emp = emp.OrderByDescending(s => s.Priority);
                    break;

                case "Priority":
                    emp = emp.OrderBy(s => s.Priority);
                    break;

                case "CreateClosedDate_desc":
                    emp = emp.OrderByDescending(s => s.TimeCreated);
                    break;

                case "CreateClosedDate":
                    emp = emp.OrderBy(s => s.TimeCreated);
                    break;

                default:
                    emp = emp.OrderByDescending(s => s.Priority);
                    break;
            }

            return View(emp.ToList());
        }

        // GET: Bugs/ShowSearchForm
        public IActionResult ShowSearchForm()
        {
            return View();
        }

        // POST: Bugs/ShowSearchResults
        public async Task<IActionResult> ShowSearchResults(String SearchPhrase)
        {
            var search = from b in _context.Bugs
                       select b;

            if (!string.IsNullOrEmpty(SearchPhrase))
            {
                search = search.Where(a => a.Tickets.Contains(SearchPhrase)
                                         || a.Description.Contains(SearchPhrase)
                                         || a.Projects.Contains(SearchPhrase)
                                         || a.TimeCreated.Contains(SearchPhrase)
                                         || a.Creator.Contains(SearchPhrase)
                                         || a.Priority.Contains(SearchPhrase));
            }
              
           
                return View("Index", await search.ToListAsync());
            

        }


        // GET: Bugs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bugs = await _context.Bugs
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bugs == null)
            {
                return NotFound();
            }

            return View(bugs);
        }

        // GET: Bugs/Create

        [Authorize]
        public IActionResult Create(string Selected1Projects)
        {
            var rawData = (from s in _context.Bugs
                           select s).ToList();
            var amp = from s in rawData
                      select s;

            if (!String.IsNullOrEmpty(Selected1Projects))
            {
                amp = amp.Where(s => s.Projects.Trim().Equals(Selected1Projects.Trim()));
            }

            var Projects = from s in amp
                                 group s by s.Projects into newGroup
                                 where newGroup.Key != null
                                 orderby newGroup.Key
                                 select new { Projects = newGroup.Key };
            ViewBag.Projects = Projects.Select(m => new SelectListItem { Value = m.Projects, Text = m.Projects }).ToList();
            ViewBag.Selected1Projects = Selected1Projects;
                   
            return View();
        }

        // POST: Bugs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Projects,Tickets,Description,Priority,DueDate,TimeCreated,Creator")] Bugs bugs)
        {

            if (ModelState.IsValid)
            {         
                _context.Add(bugs);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(bugs);
        }

        // GET: Bugs/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(string Selected2Projects, int? id)
        {
            //Choose a Project

            var rawData = (from s in _context.Bugs
                           select s).ToList();
            var amp = from s in rawData
                      select s;

            if (!String.IsNullOrEmpty(Selected2Projects))
            {
                amp = amp.Where(s => s.Projects.Trim().Equals(Selected2Projects.Trim()));

BugTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BugTracker</title>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/fontawesome/css/all.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Bugs" asp-action="Index">Bugs</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Bugs" asp-action="ShowSearchForm">Search</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>